USE [MovieDatabase]
GO
INSERT INTO [dbo].[Movies] (Title, Description, Genre) VALUES
('The Action Hero', 'A thrilling action-packed adventure', 'Action'),
('Drama Queen', 'A heart-wrenching drama of love and loss', 'Drama'),
('Laugh Out Loud', 'A hilarious comedy for all ages', 'Comedy'),
('Lost in Paradise', 'An exciting adventure in a tropical paradise', 'Adventure'),
('The Haunting', 'A spine-chilling horror experience', 'Horror'),
('Galactic Odyssey', 'An epic journey through space and time', 'Science Fiction'),
('Love Story', 'A timeless tale of love and romance', 'Romance'),
('Edge of Darkness', 'A pulse-pounding thriller with unexpected twists', 'Thriller'),
('Fantasy Realm', 'An enchanting world of magical creatures', 'Fantasy'),
('Mystery Unveiled', 'Solve the puzzle in this gripping mystery', 'Mystery'),
('Animation Magic', 'A colorful world brought to life', 'Animation'),
('Crime Chronicles', 'Dive into the world of crime and intrigue', 'Crime'),
('Family Bonds', 'A heartwarming story of family and unity', 'Family'),
('The Biographer', 'A captivating look at a remarkable life', 'Biography'),
('History Uncovered', 'Discover the past in this historical epic', 'History'),
('Symphony of Sound', 'Music that moves the soul', 'Music'),
('Wild West Tales', 'A journey into the rugged world of the West', 'Western'),
('Warriors of Honor', 'Courage and sacrifice on the battlefield', 'War'),
('The Truth Revealed', 'Explore the unknown in this documentary', 'Documentary'),
('Game of Champions', 'A story of sportsmanship and victory', 'Sport'),
('The Superhero Saga', 'Superpowers and heroism in action', 'Superhero'),
('Enchanted Kingdom', 'Fantasy adventures in a magical land', 'Fantasy'),
('Quest for Treasures', 'Embark on a treasure hunt like no other', 'Adventure'),
('Laugh Riot', 'Roll on the floor with laughter', 'Comedy'),
('Tears of Joy', 'A drama that will touch your heart', 'Drama'),
('Action Thrill', 'Non-stop action and adrenaline rush', 'Action'),
('House of Horrors', 'Face your fears in this terrifying horror', 'Horror'),
('Time Travelers', 'A journey through time and alternate realities', 'Science Fiction'),
('Whispers in the Night', 'Solve the mystery of the unseen', 'Mystery'),
('Eternal Love', 'A romantic tale of everlasting love', 'Romance');